version: '3.8'

services:
  app:
    build: .
    container_name: aquaiq-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    # Optional: If you want to use a volume for local development without rebuilding
    # volumes:
    #   - .:/app
    #   - /app/node_modules
